// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mokiniu_sistema.Models;

namespace mokiniu_sistema.Migrations
{
    [DbContext(typeof(MokiniuContext))]
    [Migration("20191206115600_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("mokiniu_sistema.Models.Mokykla", b =>
                {
                    b.Property<int>("MokyklaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RajonasId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("MokyklaId");

                    b.HasIndex("RajonasId");

                    b.ToTable("Mokyklos");
                });

            modelBuilder.Entity("mokiniu_sistema.Models.Rajonas", b =>
                {
                    b.Property<int>("RajonasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RajonasId");

                    b.ToTable("Rajonai");
                });

            modelBuilder.Entity("mokiniu_sistema.Models.Tevas", b =>
                {
                    b.Property<int>("TevasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Vardas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TevasId");

                    b.ToTable("Tevai");
                });

            modelBuilder.Entity("mokiniu_sistema.Models.Vaikas", b =>
                {
                    b.Property<int>("VaikasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MokyklaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("PridejimoKodas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TevasId")
                        .HasColumnType("int");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaikasId");

                    b.HasIndex("MokyklaId");

                    b.HasIndex("TevasId");

                    b.ToTable("Vaikai");
                });

            modelBuilder.Entity("mokiniu_sistema.Models.Mokykla", b =>
                {
                    b.HasOne("mokiniu_sistema.Models.Rajonas", "Rajonas")
                        .WithMany("Mokyklos")
                        .HasForeignKey("RajonasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mokiniu_sistema.Models.Vaikas", b =>
                {
                    b.HasOne("mokiniu_sistema.Models.Mokykla", "Mokykla")
                        .WithMany("Vaikai")
                        .HasForeignKey("MokyklaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mokiniu_sistema.Models.Tevas", "Tevas")
                        .WithMany("Vaikai")
                        .HasForeignKey("TevasId");
                });
#pragma warning restore 612, 618
        }
    }
}
